### ISSUE TITLE
Scrolling issue in Judge and Confederate panels

### ISSUE THREAD

**Issue by drwallace** [jhudsy/LoebnerPrizeProtocol#13]
I noticed that we still have the scrolling problem in the Judge and Confederate panels, but it only appears when the conversation gets long.

I found the solution here:

https://stackoverflow.com/questions/10503606/scroll-to-bottom-of-div-on-page-load-jquery

So it will work better if you change your scrolling statements to e.g.

$('#messagepaneR').scrollTop($('#messagepaneR')[0].scrollHeight);

"The other solutions here don't actually work for divs with lots of content -- it "maxes out" scrolling down to the height of the div (instead of the height of the content of the div). So they'll work, unless you have more than double the div's height in content inside of it.
Here is the correct version:

$('#div1').scrollTop($('#div1')[0].scrollHeight);

**Comment by jhudsy** [comment]
Thanks, I have updated the code.
