### ISSUE TITLE
CDN call to jQuery vs local

### ISSUE THREAD

**Issue by Dave-Morton** [jhudsy/LoebnerPrizeProtocol#3]
With regard to this incarnation of the LPP in relation to the Loebner Competition, and given that the competing bots cannot be allowed access to the Internet, I have to wonder if it would be better to have the script tags that "call" jQuery use a "local" source rather than the CDN. By this I don't necessarily mean local to the computer that the bots, judges or confederates use, but local to the computer that contains the server.js file. This would eliminate (or at least greatly reduce) the possibility of any bots gaining unfair access to the internet. Or, more likely, allow everything to work on a closed network with no web access. The following is an example of what I'm referring to:

```
<!-- the current script tag for jQuery and socket.io -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>

<!-- The tags as I propose them: -->
<script src="http://IP.ADDRESS.OF.SERVER:8080/scripts/jquery.min.js"></script>
<script src="http://IP.ADDRESS.OF.SERVER:8080/scripts//socket.io-1.4.5.js"></script>
```
Now granted, server.js would need to be modified to make this work, and I have yet to figure that part out (so far, serving the static files interferes with the socket IO and vice-versa), but once I do I can make a pull request for this.

That is, of course, if you think it's a good idea. Having this all self contained would be a good idea, IMHO.

**Comment by jhudsy** [comment]
I did plan on doing this (when I had time), so thank you for getting this started.

**Comment by Dave-Morton** [comment]
My pleasure. I've been following the Loebner Competition since it's inception, and was thrilled to learn of this new protocol, so am pleased to be able to contribute.
