### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by bwilcox-1234** [jhudsy/LoebnerPrizeProtocol#5]
It would be nice if the read me had step-by-step instructions for running things. What are the things one clicks in order on the various webpages.  Does this thing run as a demo as is, with default names, secrets, and local web addresses?

**Comment by jhudsy** [comment]
In practice, names and secrets will be changed, and web addresses will be IP addresses on a network we'll set up at Bletchley park. Regarding how to run things, please refer to the controller html file; a new round will be declared, followed by a start round, end round, scoring, and then the process will repeat.
