### ISSUE TITLE
Cannot Get /

### ISSUE THREAD

**Issue by GreggoryPeterson** [jhudsy/LoebnerPrizeProtocol#6]
When I run localhost:8080 where I expect the server to listen, I get
`Cannot Get /`
At what URL is the content served?
Also, each time, I access localhost:8080, the socket.io doesn't catch the connection, it doesn't log anything on the console except when the script is run.

**Comment by codyebberson** [comment]
The localhost:8080 server does not serve any human readable content.

Instead, use the 3 static HTML files to play the 3 different roles:
1. Use **controller/controlPanel.html** to act as administrator.  This page displays which clients are connected, and provides buttons to start/end rounds.
2. Use **clients/judge.html** to act as a judge.  This shows two chat interfaces.  It starts in read-only mode.  Once the administrator starts a round, the chat interface will be enabled.
3. Use **clients/confederate.html** to act as a human confederate.  This shows one chat interface.  Like the judge interface, it starts in read-only mode and becomes enabled when the administrator starts a round.

**Comment by jhudsy** [comment]
Closing this issue as @codyebberson is correct.
